# @Author: Alex Yorke <alexyorke>
# @Date:   2022-11-11T11:00:00-08:00
# @Email:  
# @Filename: _config.yml
# @Last modified by:   alexyorke
# @Last modified time: 2022-11-11T11:00:00-08:00
# @Copyright: Copyright (C) 2022 Alex Yorke


remote_theme: jekyll/minima
# Dependencies
markdown:         kramdown
highlighter:      rouge

plugins:
- jekyll-remote-theme
- jekyll-redirect-from

# Permalinks
permalink:        pretty

# Setup
title:            
tagline:          ''
description:      ''
url:              https://alexyorke.github.io/
baseurl:          /

author:
  name:           'Alex Yorke'
  url:

paginate:         5
google_analytics: G-2GV04PM05P
